"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, use, useEffect, useState } from "react";
import { categories, conditions } from "@/lib/catalog";
import { getBrowserSupabase } from "@/lib/supabase";
import type { Listing } from "@/lib/types";

export default function EditListingPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const router=useRouter(); const [row,setRow]=useState<Listing|null>(null); const [error,setError]=useState(""); const [saved,setSaved]=useState(false);
  useEffect(()=>{const supabase=getBrowserSupabase();if(!supabase)return;void(async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user){router.replace(`/login?next=/cuenta/anuncios/${id}/editar`);return;} const {data,error:err}=await supabase.from("listings").select("*").eq("id",id).single(); if(err){setError("No existe el anuncio o no tienes acceso.");return;} if(data.seller_id!==auth.user.id){setError("No tienes permiso para editar este anuncio.");return;} setRow(data as unknown as Listing);})();},[id,router]);
  async function save(e:FormEvent){e.preventDefault();setError("");setSaved(false);const supabase=getBrowserSupabase();if(!supabase||!row)return;const {error:err}=await supabase.from("listings").update({title:row.title,description:row.description,brand:row.brand,model:row.model,generation:row.generation,year:row.year,engine:row.engine,category:row.category,condition:row.condition,price:row.price,location:row.location,mileage:row.mileage,available_parts:row.available_parts,reference_code:row.reference_code,technical_notes:row.technical_notes,shipping_available:row.shipping_available,pickup_available:row.pickup_available,updated_at:new Date().toISOString()}).eq("id",id); if(err)setError(err.message);else setSaved(true);}
  if(error&&!row)return <div className="shell account-page"><div className="empty-state"><h1>No se puede editar</h1><p>{error}</p><Link href="/cuenta/anuncios">Volver a mis anuncios</Link></div></div>;
  if(!row)return <div className="shell account-page loading-block">Cargando anuncio…</div>;
  return <div className="shell account-page"><div className="account-head"><div><span className="kicker">EDITAR ANUNCIO</span><h1>{row.title}</h1></div><Link href={`/pieza/${row.slug}`}>Ver anuncio →</Link></div><form className="profile-form stack-form" onSubmit={save}><label>Título<input value={row.title} onChange={(e)=>setRow({...row,title:e.target.value})}/></label><div className="two-cols"><label>Marca<input value={row.brand} onChange={(e)=>setRow({...row,brand:e.target.value})}/></label><label>Modelo<input value={row.model} onChange={(e)=>setRow({...row,model:e.target.value})}/></label></div><div className="three-cols"><label>Generación<input value={row.generation??""} onChange={(e)=>setRow({...row,generation:e.target.value||null})}/></label><label>Año<input inputMode="numeric" value={row.year??""} onChange={(e)=>setRow({...row,year:e.target.value?Number(e.target.value):null})}/></label><label>Motor<input value={row.engine??""} onChange={(e)=>setRow({...row,engine:e.target.value||null})}/></label></div>{row.type==="part"&&<label>Categoría<select value={row.category??"Otros"} onChange={(e)=>setRow({...row,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label>}<label>Estado<select value={row.condition} onChange={(e)=>setRow({...row,condition:e.target.value})}>{conditions.map(x=><option key={x}>{x}</option>)}</select></label><div className="two-cols"><label>Precio<input type="number" min="0" value={row.price??""} onChange={(e)=>setRow({...row,price:e.target.value?Number(e.target.value):null})}/></label><label>Localización<input value={row.location} onChange={(e)=>setRow({...row,location:e.target.value})}/></label></div><div className="delivery-options"><label className="delivery-option"><input type="checkbox" checked={row.pickup_available!==false} onChange={(e)=>setRow({...row,pickup_available:e.target.checked})}/> Recogida en mano</label><label className="delivery-option"><input type="checkbox" checked={Boolean(row.shipping_available)} onChange={(e)=>setRow({...row,shipping_available:e.target.checked})}/> Envío disponible</label></div><label>Descripción<textarea rows={5} value={row.description??""} onChange={(e)=>setRow({...row,description:e.target.value||null})}/></label>{row.type==="vehicle"&&<label>Piezas disponibles<input value={(row.available_parts??[]).join(", ")} onChange={(e)=>setRow({...row,available_parts:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label>}{row.type==="part"&&<div className="two-cols"><label>Referencia OEM<input value={row.reference_code??""} onChange={(e)=>setRow({...row,reference_code:e.target.value||null})}/></label><label>Notas técnicas<input value={row.technical_notes??""} onChange={(e)=>setRow({...row,technical_notes:e.target.value||null})}/></label></div>}{error&&<div className="form-error">{error}</div>}{saved&&<div className="form-success">Cambios guardados.</div>}<button className="button button-primary">Guardar cambios</button></form></div>;
}
