"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase";

export default function ProfilePage() {
  const [form, setForm] = useState({ display_name:"", location:"", whatsapp:"", phone:"" }); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [userId,setUserId]=useState("");
  useEffect(() => { const supabase=getBrowserSupabase(); if(!supabase)return; void (async()=>{ const {data:auth}=await supabase.auth.getUser(); if(!auth.user){window.location.href="/login?next=/cuenta/perfil";return;} setUserId(auth.user.id); const {data}=await supabase.from("profiles").select("display_name,location,whatsapp,phone").eq("id",auth.user.id).single(); if(data)setForm({display_name:data.display_name??"",location:data.location??"",whatsapp:data.whatsapp??"",phone:data.phone??""}); })(); },[]);
  async function save(e:FormEvent){e.preventDefault();setMessage("");setError(""); const supabase=getBrowserSupabase(); if(!supabase||!userId)return; if(!form.whatsapp.trim()&&!form.phone.trim())return setError("Mantén al menos un método de contacto."); const {error:err}=await supabase.from("profiles").update({...form,updated_at:new Date().toISOString()}).eq("id",userId); if(err)setError(err.message);else setMessage("Perfil actualizado.");}
  return <div className="shell account-page"><div className="account-head"><div><span className="kicker">DATOS PÚBLICOS</span><h1>Perfil</h1></div></div><div className="account-tabs"><Link href="/cuenta/anuncios">Anuncios</Link><Link href="/cuenta/favoritos">Favoritos</Link><Link className="active" href="/cuenta/perfil">Perfil</Link></div><form className="profile-form stack-form" onSubmit={save}><label>Nombre visible<input required value={form.display_name} onChange={(e)=>setForm({...form,display_name:e.target.value})}/></label><label>Localización<input required value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></label><div className="two-cols"><label>WhatsApp<input value={form.whatsapp} onChange={(e)=>setForm({...form,whatsapp:e.target.value})}/></label><label>Teléfono<input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label></div><div className="form-hint">Estos datos se muestran para que compradores reales puedan contactarte. El email de acceso nunca se expone en el marketplace.</div>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}<button className="button button-primary">Guardar cambios</button></form></div>;
}
